#!/bin/sh

set -e -x

mkdir -p /tmp/dropbear
(cd /tmp/dropbear && \
  curl http://mirrors.kernel.org/ubuntu/pool/universe/d/dropbear/dropbear_2013.60-1ubuntu2_amd64.deb -o dropbear.deb && \
  ar -xv dropbear.deb && \
  tar -vxf data.tar.xz
)
cp /tmp/dropbear/usr/bin/dbclient ./ssh
cp /tmp/dropbear/usr/bin/dropbearkey ./ssh-keygen
rm -rf /tmp/dropbear

